-- Tumeni Phase 6.8.3 — Retention analytics and repeat-purchase engagement
create or replace function public.trigger_my_retention_engagement()
returns jsonb language plpgsql security definer set search_path = '' as $$
declare uid uuid:=auth.uid(); delivered_count bigint; last_order timestamptz; latest_activity timestamptz; lifecycle text; created_count int:=0;begin
if uid is null then return jsonb_build_object('created',false,'reason','not_authenticated'); end if;
select count(*) filter(where status='delivered'),max(created_at) filter(where status='delivered') into delivered_count,last_order from public.orders where customer_id=uid;
select max(created_at) into latest_activity from public.customer_behavior_events where customer_id=uid;
lifecycle:=case when delivered_count=0 and greatest(coalesce(last_order,'epoch'::timestamptz),coalesce(latest_activity,'epoch'::timestamptz))>now()-interval '7 days' then 'new_active' when delivered_count=0 then 'new' when last_order>=now()-interval '30 days' and delivered_count>=4 then 'high_frequency' when last_order<now()-interval '60 days' then 'at_risk' when last_order<now()-interval '30 days' then 'inactive' else 'returning' end;
if lifecycle in('at_risk','inactive') and not exists(select 1 from public.notifications where recipient_id=uid and notification_type='retention' and created_at>=now()-interval '7 days') then insert into public.notifications(recipient_id,notification_type,title,message,metadata) values(uid,'retention','Welcome back to Tumeni','We have products and services ready when you need them.',jsonb_build_object('lifecycle',lifecycle));created_count:=1;
elsif lifecycle='new' and not exists(select 1 from public.notifications where recipient_id=uid and notification_type='retention' and created_at>=now()-interval '3 days') then insert into public.notifications(recipient_id,notification_type,title,message,metadata) values(uid,'retention','Welcome to Tumeni','Explore products, services and delivery options available to you.',jsonb_build_object('lifecycle',lifecycle));created_count:=1;
elsif lifecycle='returning' and delivered_count>0 and last_order<now()-interval '21 days' and not exists(select 1 from public.notifications where recipient_id=uid and notification_type='retention_repeat' and created_at>=now()-interval '14 days') then insert into public.notifications(recipient_id,notification_type,title,message,metadata) values(uid,'retention_repeat','Ready for another Tumeni order?','Explore products and services you may need again.',jsonb_build_object('lifecycle',lifecycle));created_count:=1;end if;
return jsonb_build_object('created',created_count>0,'count',created_count,'lifecycle',lifecycle);end;$$;
revoke all on function public.trigger_my_retention_engagement() from public,anon;grant execute on function public.trigger_my_retention_engagement() to authenticated;

create or replace function public.get_admin_retention_analytics(p_days integer default 30)
returns table(period_days integer,total_customers bigint,active_customers bigint,returning_customers bigint,at_risk_customers bigint,inactive_customers bigint,new_customers bigint,repeat_customers bigint,repeat_rate numeric)
language sql stable security invoker set search_path = '' as $$
with bounds as(select now()-make_interval(days=>greatest(1,least(coalesce(p_days,30),365))) since), customer_orders as(select p.id,count(o.id) filter(where o.status='delivered') delivered_count,max(o.created_at) filter(where o.status='delivered') last_order from public.profiles p left join public.orders o on o.customer_id=p.id group by p.id), classified as(select *,case when delivered_count=0 and last_order is null then 'new' when last_order>=now()-interval '30 days' and delivered_count>=4 then 'high_frequency' when last_order<now()-interval '60 days' then 'at_risk' when last_order<now()-interval '30 days' then 'inactive' when delivered_count>0 then 'returning' else 'new' end lifecycle from customer_orders), recent as(select count(*) filter(where created_at>=b.since and status='delivered') delivered_recent from public.orders cross join bounds) select greatest(1,(select extract(day from now()-since)::int from bounds)),count(*),count(*) filter(where lifecycle in('returning','high_frequency')),count(*) filter(where lifecycle='returning'),count(*) filter(where lifecycle='at_risk'),count(*) filter(where lifecycle='inactive'),count(*) filter(where lifecycle='new'),count(*) filter(where delivered_count>=2),(count(*) filter(where delivered_count>=2)::numeric/nullif(count(*) filter(where delivered_count>=1),0)*100)::numeric(10,2) from classified;$$;
revoke all on function public.get_admin_retention_analytics(integer) from public,anon;grant execute on function public.get_admin_retention_analytics(integer) to authenticated;
notify pgrst,'reload schema';