name: Universal Web Sync 

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync Code
        run: |
          git config --global user.name 'GitHub Action Sync'
          git config --global user.email 'action@github.com'

          git remote add destination https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/innomaweta1-cmd/innocent-maweta.git

          git push destination HEAD --force
